version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./nginx/templates:/etc/nginx/templates
    - ./nginx/config.conf:/etc/nginx/conf.d/config.conf

    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=dockerhub.bvj
    - NGINX_PORT=80
    networks:
      - docker-registry
  
  registry:
    image: registry:2
    container_name: registry
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /storage
    volumes:
      - ./storage:/storage
    networks:
      - docker-registry

networks:
  docker-registry:
    driver: bridge